services:
  # Next.js Application
  app-fe:
    container_name: app-fe
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        NODE_ENV: production
        SESSION_SECRET: ${SESSION_SECRET}
        NEXT_PUBLIC_BACKEND_ENDPOINT_URL: ${NEXT_PUBLIC_BACKEND_ENDPOINT_URL}
    ports:
      - 3000:3000

networks:
  default:
    name: ${COMPOSE_NETWORK}
    external: true
