name: Code Check

on:
  push:
    branches:
      - main
      - develop

jobs:
  check_formatting:
    name: Check codebase formating
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Prettier for Code Formatting
        run: npx prettier .

  build_and_test:
    name: Run test and build code base
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm i

      - name: Build Project
        run: npm run build

      - name: Run tests
        run: npm test
